// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRecentNotes() {
  return window['go']['main']['App']['GetRecentNotes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function OpenDailyNote() {
  return window['go']['main']['App']['OpenDailyNote']();
}

export function OpenNoteAt(arg1, arg2) {
  return window['go']['main']['App']['OpenNoteAt'](arg1, arg2);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SearchNotes(arg1) {
  return window['go']['main']['App']['SearchNotes'](arg1);
}

export function SelectRootPath() {
  return window['go']['main']['App']['SelectRootPath']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
