// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRecentNotes() {
  return window['go']['main']['App']['GetRecentNotes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function OpenDailyNote() {
  return window['go']['main']['App']['OpenDailyNote']();
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}
