// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {note} from '../models';

export function GetConfig():Promise<config.AppConfig>;

export function GetRecentNotes():Promise<Array<note.NoteEntry>>;

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function OpenDailyNote():Promise<void>;

export function SaveNote(arg1:string):Promise<void>;
