// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {command} from '../models';
import {config} from '../models';
import {note} from '../models';

export function ExecuteCommand(arg1:string,arg2:Array<string>):Promise<void>;

export function GetCommands():Promise<Array<command.Command>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetRecentNotes():Promise<Array<note.NoteEntry>>;

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function OpenDailyNote():Promise<void>;

export function OpenNoteAt(arg1:string,arg2:number):Promise<void>;

export function SaveNote(arg1:string):Promise<void>;

export function SearchNotes(arg1:string):Promise<Array<note.SearchResult>>;
